### ISSUE TITLE
"no match of right hand side value: :error"

### ISSUE THREAD

**Issue by thbar** [xavier/xlsx_reader#21]
While reading an XLSX (which I cannot unfortunately share, but will be able to re-test on it if we figure this out), I got the following error:

```
** (MatchError) no match of right hand side value: :error
    (xlsx_reader 0.7.0) lib/xlsx_reader/parsers/worksheet_parser.ex:308: XlsxReader.Parsers.WorksheetParser.convert_current_cell_value/1
    (xlsx_reader 0.7.0) lib/xlsx_reader/parsers/worksheet_parser.ex:162: XlsxReader.Parsers.WorksheetParser.add_cell_to_row/1
    (xlsx_reader 0.7.0) lib/xlsx_reader/parsers/worksheet_parser.ex:109: XlsxReader.Parsers.WorksheetParser.handle_event/3
    (saxy 1.5.0) lib/saxy/emitter.ex:16: Saxy.Emitter.emit/3
    (saxy 1.5.0) lib/saxy/emitter.ex:7: Saxy.Emitter.emit/4
    (saxy 1.5.0) lib/saxy/parser/builder.ex:1191: Saxy.Parser.Binary.close_tag_name/6
    (saxy 1.5.0) lib/saxy.ex:194: Saxy.parse_string/4
```

I am using v0.7.0.

**Comment by xavier** [comment]
The parser seems to be choking on a date cell. Anything special in your setup in that regard?

**Comment by xavier** [comment]
Would you be able to bisect through your dataset to isolate which column/row is causing the issue and create a simple test file?

My hunch is that some cell has a date-like style but its actual content is not a valid serial date value.

**Comment by billylaing** [comment]
I'm having a similar uncaught error on the same place cause of a `#REF!` returning for a `:percentage` field. I'll probably fork and see if I can get something working.

**Comment by xavier** [comment]
Version 0.8.2 which has been published has improved handling for conversion errors. The library shouldn't crash anymore and the cell which couldn't be converted will contain the `"#ERROR"` placeholder.
