### ISSUE TITLE
Spec for XlsxReader.open/2 is incorrect and causes dialyzer failures

### ISSUE THREAD

**Issue by wkirschbaum** [xavier/xlsx_reader#31]
The following typespec is incorrect when adding exclude_hidden_sheets?: true as an option and fails with dialyzer: 

```elixir
  @spec open(String.t() | binary(), [source_option]) ::
          {:ok, XlsxReader.Package.t()} | error()
  def open(file, options \\ []) do
    file
    |> ZipArchive.handle(Keyword.get(options, :source, :path))
    |> PackageLoader.open(
      Keyword.take(options, [:supported_custom_formats, :exclude_hidden_sheets?])
    )
  end
  ```

with the error: 

```bash
The function call will not succeed.

XlsxReader.open(any(), [{:exclude_hidden_sheets?, true}])

breaks the contract
(String.t() | binary(), [source_option()]) :: {:ok, XlsxReader.Package.t()} | error()
```

It should allow the PackageLoader.open options as well.

**Comment by xavier** [comment]
Thanks for your report.

It might take a bit of effort to address this issue in a DRY manner but I'll see if there's some quick win solution to at least solve part of the problem.

**Comment by wkirschbaum** [comment]
I was also looking into an good fix, but gave up after a few minutes... my typespec knowledge is not there yet 😆...

**Comment by xavier** [comment]
It's not too hard to specify but doing so would involve quite a bit of repetition because the existing specs for some of these types are declared in underlying private modules which should not be exposed in the documentation of the public API...

**Comment by wkirschbaum** [comment]
@xavier thanks for the update. The recent release seems to have fixed this issue. We can close this?

**Comment by xavier** [comment]
There were no changes made which should affect this typespec issue, we can leave this issue open.

**Comment by wkirschbaum** [comment]
@xavier are you sure? https://diff.hex.pm/diff/xlsx_reader/0.8.4..0.8.5

we removed our dialyzer ignores and it passes.

**Comment by xavier** [comment]
Woopsie! It seems like I accidentally released some WIP... 🤦 

It should solve some of the typing issue but at the cost of some repetition in the code base, I'll have to clean that up...
