### ISSUE TITLE
Fail to read xlsx file correctly

### ISSUE THREAD

**Issue by laiboonh** [xavier/xlsx_reader#34]
[test-1.xlsx](https://github.com/user-attachments/files/15964433/test-1.xlsx)

I have this xlsx file when i read out the output does not match what is in the xlsx. Any idea what is wrong?

**Comment by xavier** [comment]
The date cells in the file seem to use a non-standard format. 

You can see them by inspecting `package.workbook.custom_formats`:

```elixir
%XlsxReader.Package{
  workbook: %XlsxReader.Workbook{
    base_date: ~D[1899-12-30],
    custom_formats: %{
      "0" => "General",
      "59" => "\"YYYY\"-mm-\"DD\" hh:mm:\"SS\"",
      "60" => "\"YYYY\"-mm-\"DD\"",
      "61" => "#,##0.00\" \"[$$-409]"
    },
   # ...
}
```

There seem to be some extra double quotes in the format string which cause some of the tokens to be treated as literals (e.g. `"YYYY"`).

FWIW, Numbers also seems to have issues with this format:

<img width="555" alt="image" src="https://github.com/xavier/xlsx_reader/assets/31668/40740c38-3761-4d21-b695-90cf02acfcf0">

The fix for this issue is to amend the incorrect format string in the file and use one of the default date/time formats.

If you can't fix the cell format at the source, you can always [provide a hint to the parser to map the style to supported data type](https://hexdocs.pm/xlsx_reader/0.8.5/XlsxReader.html#module-additional-custom-formats-support).

**Comment by laiboonh** [comment]
Can we use this sample file instead
[test-1.xlsx](https://github.com/user-attachments/files/15981184/test-1.xlsx)

I tried 
```
{:ok, package} =
      XlsxReader.open(dashboard_data_filename(),
        supported_custom_formats: [
        {~r/\d+(?:\.?\d+)? US\$/, :number}
        ]
      )
 {:ok, rows} = XlsxReader.sheet(package, sheet_name, number_type: Decimal)
```
nothing happened to column 11. I was hoping it will be converted to number or Decimal

I also tried 
```
supported_custom_formats: [{~r"^(\d{2})\/(\d{2})\/(\d{4})\s(\d{2})\:(\d{2})\:(\d{2})\SAM", :date_time}]
```
this did nothing to the date time columns 3 & 4

I tried something silly 
```
supported_custom_formats: [{~r"YYYY-MM-DD HH:MM:SS", :date_time}]
```
this converted non date time column 6 & 8 wrongly

**Comment by xavier** [comment]
I have [fixed a bug in the sheet parser](https://github.com/xavier/xlsx_reader/commit/99611e516a87b163dd9f30255bdb2fa9b11fc234). Could your test if `master` solves your issue?

**Comment by laiboonh** [comment]
I tried
```
 {:ok, package} =
      XlsxReader.open(dashboard_data_filename(),
        supported_custom_formats: [
          {"YYYY-MM-DD HH:MM:SS", :date_time},
          {"0.00 [$USD]", :number}
        ]
      )
```
Dates are showing correctly as NaiveDateTime now. However currency is still appearing as strings. Could you explain how should one use `supported_custom_formats` correctly. According to the docs it seems to suggest one should use regular expression but seemingly "YYYY-MM-DD HH:MM:SS" works. Which is baffling to me

**Comment by xavier** [comment]
The problem with your file is that the cell which holds the monetary value has no style attribute at all:

```xml
<c r="H2">
  <v>100.05</v>
</c>
```
So we default to returning this data as a string.

Based on the custom styles defined in `test-1.xlsx` above, I would expect that cell to be written as:

```xml
<c r="H2" s="166">
  <v>100.05</v>
</c>
```

Where `166` is the style ID for `#,##0.00 [$USD]`. Which could then be mapped to `:number` by a `supported_custom_formats` matcher.

Which software or library was used to write this file?

**Comment by laiboonh** [comment]
Thanks for checking this out. I got this file from a third party so am not sure what was used to generate the file.

Can you share with me why `{"YYYY-MM-DD HH:MM:SS", :date_time}` works? `"YYYY-MM-DD HH:MM:SS"` is just a string and not even a regular expression but somehow this works.

**Comment by xavier** [comment]
Unlike the amount, these cells have a style attribute:

```xml
<c r="C2" s="1">
  <v>45469.0397569444</v>
</c>
<c r="D2" s="1">
  <v>45469.0497800926</v>
</c>
```
The reason that didn't work earlier was because of the bug which was fixed.

**Comment by laiboonh** [comment]
I see thanks for explaining. For anyone who is like me trying to make things work you can refer to `custom_formats` in package
```
custom_formats: %{
      "164" => "YYYY-MM-DD HH:MM:SS",
      "165" => "YYYY-MM-DD",
      "166" => "#,##0.00 [$USD]",
      "167" => "#,##0.00 [$EUR]",
      "168" => "#,##0.00 [$AED]",
      "169" => "#,##0.00 [$TRY]"
    }
```
Take one of the strings mentioned above and give the corresponding type as such
```
{:ok, package} =
      XlsxReader.open(dashboard_data_filename(),
        supported_custom_formats: [
          {"YYYY-MM-DD HH:MM:SS", :date_time}
        ]
      )
```
