### ISSUE TITLE
Integers being parsed as dates.

### ISSUE THREAD

**Issue by bryanweatherly** [xavier/xlsx_reader#35]
I'm getting the following error when attempting to read sheets:

    ** (FunctionClauseError) no function clause matching in Calendar.ISO.date_from_iso_days/1

    The following arguments were given to Calendar.ISO.date_from_iso_days/1:

        # 1
        5576483589

    Attempted function clauses (showing 1 out of 1):

        def date_from_iso_days(days) when is_integer(days) and days >= -3_652_059 and days <= 3_652_424

    (elixir 1.16.3) lib/calendar/iso.ex:812: Calendar.ISO.date_from_iso_days/1
    (elixir 1.16.3) lib/calendar/date.ex:710: Date.add/2
    (xlsx_reader 0.8.5) lib/xlsx_reader/conversion.ex:243: XlsxReader.Conversion.to_date/2
    (xlsx_reader 0.8.5) lib/xlsx_reader/parsers/worksheet_parser.ex:394: XlsxReader.Parsers.WorksheetParser.convert_current_cell_value/1
    (xlsx_reader 0.8.5) lib/xlsx_reader/parsers/worksheet_parser.ex:328: XlsxReader.Parsers.WorksheetParser.format_cell_data/1
    (xlsx_reader 0.8.5) lib/xlsx_reader/parsers/worksheet_parser.ex:224: XlsxReader.Parsers.WorksheetParser.add_cell_to_row/1
    (xlsx_reader 0.8.5) lib/xlsx_reader/parsers/worksheet_parser.ex:129: XlsxReader.Parsers.WorksheetParser.handle_event/3
    (saxy 1.5.0) lib/saxy/emitter.ex:16: Saxy.Emitter.emit/3
    (saxy 1.5.0) lib/saxy/emitter.ex:7: Saxy.Emitter.emit/4
    (saxy 1.5.0) lib/saxy/parser/builder.ex:1191: Saxy.Parser.Binary.close_tag_name/6
    (saxy 1.5.0) lib/saxy.ex:194: Saxy.parse_string/4
    (xlsx_reader 0.8.5) lib/xlsx_reader.ex:257: anonymous fn/4 in XlsxReader.sheets/2
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (xlsx_reader 0.8.5) lib/xlsx_reader.ex:256: XlsxReader.sheets/2

The sheet I'm attempting to parse contains an unformatted, 10-digit integer, which is being interpreted as a `:date`, but then causing an error in the date conversion. I ultimately what this cell to be interpreted as a `:string`. It seems like I can work around this using a [custom format](https://hexdocs.pm/xlsx_reader/0.8.5/XlsxReader.html#module-additional-custom-formats-support), but I'm unsure of the syntax to make this work.

**Comment by xavier** [comment]
It seems like the cell with that 10 digit integer in the source file has been assigned [a format which we map to a date by default](https://github.com/xavier/xlsx_reader/blob/a17fab98fed27c8e1dcd4faee892258e05632c30/lib/xlsx_reader/styles.ex#L79) or is misusing one of the [known styles](https://github.com/xavier/xlsx_reader/blob/master/lib/xlsx_reader/styles.ex#L12).

The  custom format matcher matches the format string associated with the cell by the authoring software. 
You can view the format string by editing the cell style in your spreadsheet software of choice.
You can then inspect the custom format strings declared in the document to identify the problematic one and use this as a key to force the value format, .e.g. `[{"mmm yy", :string}]`.

Could you share the contents of `package.workbook.custom_formats` for this file?

**Comment by bryanweatherly** [comment]
[Book6.xlsx](https://github.com/user-attachments/files/15980150/Book6.xlsx)

Here's an example of a workbook with the issue. I can't share the original file, and I was unable to replicate this issue by manually inputting 10 digit integers in Excel. The attached is a modified version of the original file.

The output of `package.workbook.custom_formats` for the attached workbook is an empty map.

**Comment by xavier** [comment]
I have [fixed a bug in the sheet parser](https://github.com/xavier/xlsx_reader/commit/99611e516a87b163dd9f30255bdb2fa9b11fc234). Could your test if `master` solves your issue?

**Comment by bryanweatherly** [comment]
`master` does indeed solve it:
```

iex(4)>     {:ok, sheets} = XlsxReader.sheets(package)
{:ok,
 [
   {"Sheet 1",
    [
      ["Number", "Name", "Effective Date", "ID Number", "Operator", "County",
       "State", "Product", "Description", "Acres"],
      ["Number", "Name", ~D[2024-07-01], "5575789630", "Operator", "County",
       "State", "Product", "Description", "Acres"]
    ]}
 ]}
```

Thanks for the fast turn around on this!

**Comment by xavier** [comment]
Thanks for the feedback, I have no idea how this bug didn't surface earlier. 🤔
