### ISSUE TITLE
ISO8601 date conversion

### ISSUE THREAD

**Issue by darraghenright** [xavier/xlsx_reader#4]
Hi there! 

Great library! I'm just trying it out here, nice clear API and documentation.

I'm not sure if this is an issue or not—apologies if not, but I figured I'd ask to clarify:

In an example .xlsx file I was testing I noticed an ISO8601 formatted date (e.g: `2020-05-17` was returned as `43968.0`. 

This confused me at first but I quickly discovered that this is a serial date, thanks to the [Dates And Times in Excel](http://www.cpearson.com/excel/datetime.htm) article you linked in `conversion.ex`.

The same date formatted as `17/5/2020` in another cell was returned as a date sigil, so I guess I expected that the ISO8601 formatted date would be returned as a date sigil too. Or is this expected behaviour?

Thanks!

**Comment by xavier** [comment]
Thanks for your feedback. 👍 

Determining with perfect accuracy a cell type is kind of a best effort situation. There a few actual cell types but unfortunately date is not one of those. The only way to detect that a cell contains a date is to match its style id against some [magic numbers](https://github.com/xavier/xlsx_reader/blob/master/lib/xlsx_reader/styles.ex#L9) (which probably date back from the late 80s) or [introspect the format string](https://github.com/xavier/xlsx_reader/blob/master/lib/xlsx_reader/styles.ex#L76).

I guess it would be reasonable to support ISO date(time) in the default custom formats. Let me know if you feel like opening a PR or I'll try to do this myself when I get some spare time this week.

**Comment by xavier** [comment]
Thanks for your contribution! 👍
